[tool.poetry]
name = "kuflow-sdk-python"
version = "0.4.0.dev3"
description = "KuFlow packages to build awesome clients"
license = "MIT"
authors = ["KuFlow S.L. <kuflow@kuflow.com>"]
homepage = "https://kuflow.com/"
documentation = "https://docs.kuflow.com/"
repository = "https://github.com/kuflow/kuflow-sdk-python"
readme = "README.md"
include = ["VERSION", "README.md"]

[build-system]
requires = ["poetry_core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.commitizen]
name = "cz_conventional_commits"
version = "0.4.0.dev3"
tag_format = "v$version"
version_files = [
    "VERSION",
    "pyproject.toml:^version",
    "kuflow-rest/VERSION",
    "kuflow-rest/pyproject.toml:^version",
    "kuflow-rest/kuflow_rest/__init__.py:^__version",
    "kuflow-robotframework/VERSION",
    "kuflow-robotframework/pyproject.toml:^version",
    "kuflow-robotframework/KuFlow/__init__.py:^__version",
    ]
update_changelog_on_bump = true
changelog_incremental = true
bump_message = "bump: $current_version → $new_version"


[tool.poetry.dependencies]
python = "~3.8"

[tool.poetry.dev-dependencies]
ipython = "^7.29.0"
mypy = "0.910"
flake8 = "4.0.1"
dunamai = "^1.7.0"
commitizen = "^2.20.3"
